[YouTube-Music]
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
excluded-patches = "'Custom branding' 'Theme'"
arch = "arm64-v8a"
build-mode = "apk"

[YouTube-Music]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
excluded-patches = "'Custom branding' 'Theme'"
arch = "arm64-v8a"
build-mode = "apk"

[Symfonium]
patches-source = "binarymend/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://symfonium.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "apk"

[Trakt]
patches-source = "PixelPusher247/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://trakt.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "apk"
